apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubean.fullname" . }}
  namespace: {{ include "kubean.namespace" . }}
  labels:
    {{- include "kubean.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubeanOperator.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubean.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kubeanOperator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubean.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kubeanOperator.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubean.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kubeanOperator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.kubeanOperator.securityContext | nindent 12 }}
          image: "{{ .Values.kubeanOperator.image.registry }}/{{ .Values.kubeanOperator.image.repository }}:{{ .Values.kubeanOperator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kubeanOperator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.kubeanOperator.resources | nindent 12 }}
      {{- with .Values.kubeanOperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeanOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeanOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
