
apiVersion: kubean.io/v1alpha1
kind: Manifest
metadata:
  name: "manifest-2.28-a59585b"
  labels:
    kubean.io/sprayRelease: "2.28"
  annotations:
    kubean.io/sprayTimestamp: "1752219088"
    kubean.io/sprayRelease: "2.28"
    kubean.io/sprayCommit: "a59585b"
    helm.sh/resource-policy: keep
spec:
  kubesprayVersion: "a59585b6dcb731b91690cd8299b518fa36eab82e"
  kubeanVersion: ""
  docker:
    - os: redhat
      defaultVersion: "28.0"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
    - os: debian
      defaultVersion: "28.0"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "25.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
    - os: ubuntu
      defaultVersion: "28.0"
      versionRange:
        - "18.09"
        - "19.03"
        - "20.10"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
        - "27.0"
        - "27.1"
        - "27.2"
        - "27.3"
        - "27.4"
        - "27.5"
        - "28.0"
    - os: kylin
      defaultVersion: "26.1"
      versionRange:
        - "18.09"
        - "19.03"
        - "23.0"
        - "24.0"
        - "26.0"
        - "26.1"
  components:
    - name: cilium
      defaultVersion: "1.17.3"
      versionRange: []
    - name: flannel
      defaultVersion: "0.22.0"
      versionRange: []
    - name: kube_ovn
      defaultVersion: "1.12.21"
      versionRange: []
    - name: runc
      defaultVersion: "1.2.6"
      versionRange:
        - "1.2.6"
        - "1.2.5"
        - "1.2.4"
        - "1.2.3"
        - "1.2.2"
        - "1.2.1"
        - "1.2.0"
        - "1.1.15"
        - "1.1.14"
        - "1.1.13"
        - "1.1.12"
        - "1.1.11"
        - "1.1.10"
        - "1.1.9"
        - "1.1.8"
    - name: kube
      defaultVersion: "1.32.6"
      versionRange:
        - "1.32.6"
        - "1.32.5"
        - "1.32.4"
        - "1.32.3"
        - "1.32.2"
        - "1.32.1"
        - "1.32.0"
        - "1.31.10"
        - "1.31.9"
        - "1.31.8"
        - "1.31.7"
        - "1.31.6"
        - "1.31.5"
        - "1.31.4"
        - "1.31.3"
        - "1.31.2"
        - "1.31.1"
        - "1.31.0"
        - "1.30.14"
        - "1.30.13"
        - "1.30.12"
        - "1.30.11"
        - "1.30.10"
        - "1.30.9"
        - "1.30.8"
        - "1.30.7"
        - "1.30.6"
        - "1.30.5"
        - "1.30.4"
        - "1.30.3"
        - "1.30.2"
        - "1.30.1"
        - "1.30.0"
    - name: cni
      defaultVersion: "1.4.1"
      versionRange:
        - "1.4.1"
        - "1.4.0"
        - "1.3.0"
        - "1.2.0"
        - "1.1.1"
        - "1.1.0"
        - "1.0.1"
        - "1.0.0"
    - name: calico
      defaultVersion: "3.29.4"
      versionRange:
        - "3.29.4"
        - "3.29.3"
        - "3.29.2"
        - "3.29.1"
        - "3.29.0"
        - "3.28.5"
        - "3.28.4"
        - "3.28.3"
        - "3.28.2"
        - "3.28.1"
        - "3.28.0"
        - "3.27.5"
        - "3.27.4"
        - "3.27.3"
        - "3.27.2"
        - "3.27.0"
    - name: containerd
      defaultVersion: "2.0.5"
      versionRange:
        - "2.0.5"
        - "2.0.4"
        - "2.0.3"
        - "2.0.2"
        - "2.0.1"
        - "2.0.0"
        - "1.7.27"
        - "1.7.26"
        - "1.7.25"
        - "1.7.24"
        - "1.7.23"
        - "1.7.22"
        - "1.7.21"
        - "1.7.20"
        - "1.7.19"
        - "1.7.18"
        - "1.7.17"
        - "1.7.16"
        - "1.7.15"
        - "1.7.14"
        - "1.7.13"
        - "1.7.12"
        - "1.7.11"
        - "1.7.10"
        - "1.7.9"
        - "1.7.8"
        - "1.7.7"
        - "1.7.6"
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
        - "1.6.38"
        - "1.6.37"
        - "1.6.36"
        - "1.6.35"
        - "1.6.34"
        - "1.6.33"
        - "1.6.32"
        - "1.6.31"
        - "1.6.30"
        - "1.6.28"
        - "1.6.27"
        - "1.6.26"
        - "1.6.25"
        - "1.6.24"
        - "1.6.23"
        - "1.6.22"
        - "1.6.21"
        - "1.6.20"
        - "1.6.19"
        - "1.6.18"
        - "1.6.17"
        - "1.6.16"
        - "1.6.15"
        - "1.6.14"
