apiVersion: "kubean.io/v1alpha1"
kind: "Manifest"
metadata:
  name: "manifest-2.23-72da838"
  labels:
    kubean.io/sprayRelease: "2.23"
  annotations:
    kubean.io/sprayTimestamp: "1700228040"
    kubean.io/sprayRelease: "2.23"
    kubean.io/sprayCommit: "72da838"
spec:
  kubesprayVersion: "72da8385197dc9f9a5a698d111bdc7553d5c0563"
  kubeanVersion: ""
  docker:
    - os: "redhat-7"
      defaultVersion: "20.10"
      versionRange:
        - latest
        - "18.09"
        - "19.03"
        - "20.10"
        - stable
        - edge
    - os: "debian"
      defaultVersion: "20.10"
      versionRange:
        - latest
        - "18.09"
        - "19.03"
        - "20.10"
        - stable
        - edge
    - os: "ubuntu"
      defaultVersion: "20.10"
      versionRange:
        - latest
        - "18.09"
        - "19.03"
        - "20.10"
        - stable
        - edge
  components:
    - name: "cni"
      defaultVersion: "v1.3.0"
      versionRange:
        - "v1.3.0"
        - "v1.2.0"
        - "v1.1.1"
        - "v1.1.0"
        - "v1.0.1"
        - "v1.0.0"
        - "v0.9.1"
    - name: "containerd"
      defaultVersion: "1.7.5"
      versionRange:
        - "1.7.5"
        - "1.7.4"
        - "1.7.3"
        - "1.7.2"
        - "1.7.1"
        - "1.7.0"
        - "1.6.23"
        - "1.6.22"
        - "1.6.21"
        - "1.6.20"
        - "1.6.19"
        - "1.6.18"
        - "1.6.17"
        - "1.6.16"
        - "1.6.15"
        - "1.6.14"
        - "1.6.13"
        - "1.6.12"
        - "1.6.11"
        - "1.6.10"
        - "1.6.9"
        - "1.6.8"
        - "1.6.7"
        - "1.6.6"
        - "1.6.5"
        - "1.6.4"
        - "1.6.3"
        - "1.6.2"
        - "1.6.1"
        - "1.6.0"
        - "1.5.18"
        - "1.5.17"
        - "1.5.16"
        - "1.5.15"
        - "1.5.14"
    - name: "kube"
      defaultVersion: "v1.27.7"
      versionRange:
        - "v1.27.7"
        - "v1.27.6"
        - "v1.27.5"
        - "v1.27.4"
        - "v1.27.3"
        - "v1.27.2"
        - "v1.27.1"
        - "v1.27.0"
        - "v1.26.10"
        - "v1.26.9"
        - "v1.26.8"
        - "v1.26.7"
        - "v1.26.6"
        - "v1.26.5"
        - "v1.26.4"
        - "v1.26.3"
        - "v1.26.2"
        - "v1.26.1"
        - "v1.26.0"
        - "v1.25.15"
        - "v1.25.14"
        - "v1.25.13"
        - "v1.25.12"
        - "v1.25.11"
        - "v1.25.10"
        - "v1.25.9"
        - "v1.25.8"
        - "v1.25.7"
        - "v1.25.6"
        - "v1.25.5"
        - "v1.25.4"
        - "v1.25.3"
        - "v1.25.2"
        - "v1.25.1"
        - "v1.25.0"
    - name: "calico"
      defaultVersion: "v3.25.2"
      versionRange:
        - "v3.26.1"
        - "v3.26.0"
        - "v3.25.2"
        - "v3.25.1"
        - "v3.25.0"
        - "v3.24.6"
        - "v3.24.5"
        - "v3.24.4"
        - "v3.24.3"
        - "v3.24.2"
        - "v3.24.1"
        - "v3.24.0"
        - "v3.23.5"
        - "v3.23.4"
        - "v3.23.3"
        - "v3.23.2"
        - "v3.23.1"
        - "v3.23.0"
        - "v3.22.5"
        - "v3.22.4"
        - "v3.22.3"
    - name: "cilium"
      defaultVersion: "v1.13.4"
      versionRange: []
    - name: "flannel"
      versionRange: []
      defaultVersion: "v0.22.0"
    - name: "kube-ovn"
      versionRange: []
      defaultVersion: "v1.11.5"
    - name: "etcd"
      defaultVersion: "v3.5.9"
      versionRange:
        - "v3.5.9"
        - "v3.5.8"
        - "v3.5.7"
        - "v3.5.6"
        - "v3.5.5"
        - "v3.5.4"
        - "v3.5.3"
