apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubean.fullname" . }}
  namespace: {{ include "kubean.namespace" . }}
  labels:
    {{- include "kubean.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubeanOperator.service.type }}
  ports:
    - port: {{ .Values.kubeanOperator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubean.selectorLabels" . | nindent 4 }}
