name: Auto OFFLINE CI
on:
  workflow_dispatch:
  schedule:
    # every day 14:00(UTC) = 22:00ï¼ˆBeijing),
    - cron: '0 20 * * *'

jobs:
  offline_e2e:
    runs-on: [self-hosted, offline]
    timeout-minutes: 900
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        #- uses: actions/setup-go@v3
        # with:
        #  go-version: 1.20.4

      - name: offline_e2e
        env:
          VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
          VSPHERE_PASSWD: ${{ secrets.VSPHERE_PASSWD }}
          AMD_ROOT_PASSWORD: ${{ secrets.AMD_ROOT_PASSWORD }}
          KYLIN_VM_PASSWORD: ${{ secrets.KYLIN_VM_PASSWORD }}
        run: |
          CONTAINER_TAG=$(git describe --tags --abbrev=8 --dirty)
          HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1}'`
          TAG_SECOND_PART=`echo ${CONTAINER_TAG}|awk  -F "-" '{print $2 }'`
          if [[ ${TAG_SECOND_PART} =~ rc[0-9]+ ]];then 
            HELM_CHART_VERSION=`echo ${CONTAINER_TAG}|awk -F "-" '{print $1"-"$2 }'`
          fi
          echo ${{ runner.name }}
          bash hack/offline-e2e.sh  "${HELM_CHART_VERSION}" "${VSPHERE_USER}" "${VSPHERE_PASSWD}" "${AMD_ROOT_PASSWORD}" "${KYLIN_VM_PASSWORD}"  "${{ runner.name }}"